language: java
env:
  global:
    secure: "bEagBH1ChkGMxsPCHLA+FBmRZEwqntkrz1Wipy7STA9xqpoIqpjKxy2hfLJdtD5vf0ambHog68TtlC+Y2S0gXExm4ahHA7/IPFQGNgZUnpjm+vjfm35LJH8sdHPxxo7PP8RgQp1deTVimAIr6hcenEYWuIVbUJM0ENCe+SdJ04A="
before_script:
- cd bundles/org.obeonetwork.dsl.dart.documentation
- npm install -g bower
- bower install
- cd ../../releng/org.obeonetwork.dsl.dart.releng/launcher
script: mvn clean verify
after_script:
- pwd
- cd ../../../
- ls
- chmod a+x travis-promote.sh
- ./travis-promote.sh
jdk: oraclejdk7